export const SET_BASIC_USER_INFO = "SET_BASIC_USER_INFO";
export const AUTHENTICATE = "AUTHENTICATE";
export const DEAUTHENTICATE = "DEAUTHENTICATE";
export const RESTORE_AUTH_STATE = "RESTORE_AUTH_STATE";
export const SET_BLOG_TITLES = "SET_BLOG_TITLES";
