export const SET_BASIC_USER_INFO = "SET_BASIC_USER_INFO";
export const AUTHENTICATE = "AUTHENTICATE";
export const DEAUTHENTICATE = "DEAUTHENTICATE";
export const RESTORE_AUTH_STATE = "RESTORE_AUTH_STATE";
export const SET_BLOG_TITLES = "SET_BLOG_TITLES";
export const SET_BLOG_TITLE = "SET_BLOG_TITLE";
export const SELECTED_BLOG_DATA = "SELECTED_BLOG_DATA";
export const SET_BLOGS_DATA = "SET_BLOGS_DATA";
