import axios from "axios";
import Head from "next/head";
import { useState } from "react";
import { Image } from "cloudinary-react";
const Home = () => {
  const [imageSelected, setImageSelected] = useState("");
  const [url, setUrl] = useState("");
  const uploadImage = () => {
    const formData = new FormData();
    formData.append("file", imageSelected);
    formData.append("upload_preset", "itlab_image_store_preset");
    axios
      .post("https://api.cloudinary.com/v1_1/dl8hmamey/image/upload", formData)
      .then((res) => {
        console.log("res");
        console.log(res);
        if (res) {
          setUrl(res.data.url);
        }
      });
  };
  return (
    <div>
      <Head>
        <title>Interview Experiences</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <input
        type={"file"}
        onChange={(event) => {
          setImageSelected(event.target.files[0]);
        }}
      ></input>
      <button onClick={uploadImage}>Upload Image</button>
      <Image
        style={{
          width: "100px",
          height: "100px",
          borderRadius: "50%",
          marginTop: "50px",
        }}
        cloudName={"dl8hmamey"}
        publicId={url}
      />
    </div>
  );
};

export default Home;
