import Head from "next/head";
import BlogPage from "../src/container/BlogPage/BlogPage.jsx";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BlogPage />
    </div>
  );
}
