import Head from "next/head";
import { useState } from "react";
import { connect } from "react-redux";
import { setBasicUserInfo } from "../store/actions/main";
import Carousel from "react-bootstrap/Carousel";
import "bootstrap/dist/css/bootstrap.min.css";

import styles from "./Main.module.scss";
const Home = (props) => {
  const { basicUserInfo, setBasicUserInfo, auth } = props;
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [imageUrl, setImageUrl] = useState("");
  import { Login } from "./login";
  return (
    <div>
      <Head>
        <title>Interview Experiences</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p>Enter a Name {basicUserInfo.name}:</p>
        <p>Enter a Email {basicUserInfo.email}:</p>
        <p>Enter a imageUrl {basicUserInfo.imageUrl}:</p>
        <input
          type="text"
          value={name}
          onChange={(e) => setName(e.target.value)}
        ></input>
        <input
          type="text"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
        ></input>
        <input
          type="text"
          value={imageUrl}
          onChange={(e) => setImageUrl(e.target.value)}
        ></input>
        <button
          onClick={() =>
            setBasicUserInfo({ name: name, email: email, imageUrl: imageUrl })
          }
        >
          Submit
        </button>
      </div>
      <div className={styles.some_div}>
        <Carousel>
          <Carousel.Item>
            <img
              className="d-block w-100"
              src="/assets/images/mySelf.jpg"
              alt="First slide"
            />
            <Carousel.Caption>
              <h3>First slide label</h3>
              <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
            </Carousel.Caption>
          </Carousel.Item>
          <Carousel.Item>
            <img
              className="d-block w-100"
              src="/assets/images/mySelf.jpg"
              alt="Second slide"
            />

            <Carousel.Caption>
              <h3>Second slide label</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </Carousel.Caption>
          </Carousel.Item>
          <Carousel.Item>
            <img
              className="d-block w-100"
              src="/assets/images/mySelf.jpg"
              alt="Third slide"
            />

            <Carousel.Caption>
              <h3>Third slide label</h3>
              <p>
                Praesent commodo cursus magna, vel scelerisque nisl consectetur.
              </p>
            </Carousel.Caption>
          </Carousel.Item>
        </Carousel>
      </div>
    </div>
  );
};

const mapStateToProps = (state) => {
  return { basicUserInfo: state.main.basicUserInfo, auth: state.auth };
};

const mapDispatchToProps = {
  setBasicUserInfo,
};

export default connect(mapStateToProps, mapDispatchToProps)(Home);
